name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 部署到的目标分支
          folder: .     # 需要部署的文件夹，通常是 dist 或 build